SELECT HICN
      ,MBR_LAST_NAME
      ,MBR_FIRST_NAME
      ,MBR_MIDDLE
      ,GENDER_CODE
      ,MBR_DOB
      ,RECORD_TYPE
      ,CMS_CONTRACT
      ,HOSPICE_IND
      ,TRC_CODE
      ,TC_CODE
      ,TRC_SHORT_NAME
      ,ACCRETION_EFF_DATE
      ,TRANS_DATE
      ,FILE_UPLOAD_DATE
      ,VARIABLE_DATA
  FROM SYSTEM.Humana_TRR_SRC